accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/",views.signup_view, name="signup"),
    path("login/",views.login_view, name="login"),
    path("logout/",views.logout_view, name="logout")
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list,name="list"),
    path("create/", views.article_create, name="create"),
    path('<str:slug>/', views.article_detail, name="detail")
]

djangopract/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path('about/', views.about),
    path('',views.home)
]

urlpatterns += staticfiles_urlpatterns() # check i we are in debug mode and serve the static file

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)
    thumbnail = models.ImageField(default="default.png", blank=True)
    author = models.ForeignKey(User, default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + "..."

    

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title","body","slug","thumbnail"]

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect("articles:list")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html",{"form":form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in user
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("articles:list")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html",{"form":form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("articles:list")

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html",{"articles":articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, "articles/article_detail.html",{"article":article})


@login_required()
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to do
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("articles:list")
    else:
        form = forms.CreateArticle()
    return render(request, "articles/article_create.html",{"form":form})

djangopract/views.py
from django.http import HttpResponse
from django.shortcuts import render
def about(request):
    # return HttpResponse("About")
    return render(request, "aboutpage.html")

def home(request):
    # return HttpResponse("Home")
    return render(request,"homepage.html")

accounts/templates/accounts/login.html
{% extends "base_layout.html" %}

{% block content %}

<div>

    <form id="contact-me" method="POST" action="/accounts/login/" class="w-full mx-auto max-w-3xl  shadow p-8 text-white ">
        {% csrf_token %}

        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}"/>
        {% endif %}
        <input class="bg-gray-950 px-5 py-2 rounded block" type="submit" value="login" />
    </form>
</div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base_layout.html" %}

{% block content %}

<div>

    <form id="contact-me" method="POST" action="/accounts/signup/" class="w-full mx-auto max-w-3xl  shadow p-8 text-white ">
        {% csrf_token %}

        {{form}}
        <input class="bg-gray-950 px-5 py-2 rounded block" type="submit" value="Signup" />
    </form>
</div>

{% endblock content %}

articles/templates/articles/article_create.html
{% extends "base_layout.html" %}
{% load static %}
{% block content %}
<h2 class="font-normal text-2xl leading-8 text-white my-3 ml-5">Add Article</h2>
<form class="text-white" action="{% url "articles:create" %}" method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create" class=""/>
</form>
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends "base_layout.html" %}
{% block content %}

<div class="relative isolate overflow-hidden">

    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h2 class="text-4xl font-bold tracking-tight text-white sm:text-6xl">{{article.title}}</h2>
      </div>
      <div class="mx-auto mt-10 max-w-2xl lg:mx-0 lg:max-w-none">
        <div class="grid grid-cols-1 gap-x-8 gap-y-6 text-base font-semibold leading-7 text-white sm:grid-cols-2 md:flex lg:gap-x-10">
            <img src="{{article.thumbnail.url}}" />
        </div>

        <div class="grid grid-cols-1 gap-x-8 gap-y-6 text-base font-semibold leading-7 text-white sm:grid-cols-2 md:flex lg:gap-x-10">
            <p class="mt-4">{{article.body}}</p>
        </div>

      </div>
    </div>
  </div>
  
{% endblock content %}

articles/templates/articles/article_list.html
{% extends "base_layout.html" %}
{% load static %}
{% block content %}
<h2 class="font-normal text-2xl leading-8 text-white my-3 ml-5">Article List</h2>

<div class="grid md:grid-cols-3 sm:grid-cols-2">
    {% for article in articles %}
    <div class="container mx-auto my-5">
        <div class="bg-white max-w-sm mx-auto rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer">
          <div class="h-20 bg-red-500 flex items-center justify-between">
            <h1 class="text-white ml-4 border-2 py-2 px-4 rounded-full">{{article.id}}</h1>
            {% comment %} <p class="mr-20 text-white text-lg">{{article.title}}</p> {% endcomment %}
            <p class="mr-4 text-white font-thin text-lg"><a href="{% url 'articles:detail' slug=article.slug%}">{{article.title}}</a></p>
          </div>
    
          <p class="py-6 text-lg tracking-wide ml-16">{{article.snippet}} </p>
          <hr >
          <div class="flex justify-between px-5 mb-2 text-sm text-gray-600">
            <p>Last Update</p>
            <p>{{article.date}}</p>
          </div>
        </div>
      </div>

    {% endfor %}
</div>

{% endblock content %}

templates/aboutpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <h1>We like django</h1>
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    
</head>
<body>
   <div class="">
      
      <!-- component -->
<div class="relative shadow">
   <div class="w-full backdrop-blur-sm">
       <div class="relative z-1 h-16 mx-auto px-5 max-w-7xl flex items-center justify-between text-white">
         <h1><a href="{% url 'articles:list' %}"> <img src="{% static 'logo.png'%}"/> </a> </h1>
           <ul class="flex items-center gap-5">
               <li><a class="hover:text-cyan-400 transition-colors" href="">Link 1</a></li>
               <li><a class="hover:text-cyan-400 transition-colors" href="">Link 2</a></li>
               <li><a class="hover:text-cyan-400 transition-colors" href="">Link 3</a></li>
               <li><a class="hover:text-cyan-400 transition-colors" href="">Link 4</a></li>
               <li> 
                  <form action="/accounts/logout/" method="POST">
                     {% csrf_token %}
                     <input class="" type="submit" value="Logout"/>
                  </form>   
               </li>
           </ul>
       </div>
   </div>
</div>
{% block content %}{% endblock content %}
   </div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Welcome to djangonautic </h1>
</body>
</html>